title: Noah Schlosser - Somatic Bodywork and Deep Massages
email:
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
sass:
  sass_dir: _sass
include:
  - '_pages'
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

navigation:
  - title: Home
    url: /

gems:
  - jekyll-seo-tag